---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluecore
description: Custom ucore image for my server.

# Base image
base-image: ghcr.io/ublue-os/ucore
image-version: stable

modules:
  # Copies custom system configurations
  - type: files
    files:
      - source: system
        destination: /

  # Installs useful CLI administration tools
  - type: dnf
    install:
      packages:
        - micro
        - fastfetch

  # Enables systemd services and timers
  - type: systemd
    system:
      enable:
        - cockpit.service

  # Sets up container image signing policies
  - type: signing
  
